version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: wichtel
  MYSQL_PASSWORD: wichteldev123
  MYSQL_DATABASE: wichtel
  REACT_APP_SERVER_PORT: 8000

services:
  mysql:
    image: mysql:latest
    environment:
      <<: *common-variables
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/initDbStructure.sql:/docker-entrypoint-initdb.d/initDbStructure.sql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:81
    restart: always
  server:
    build: ./server
    depends_on:
      - mysql
    expose:
      - 8000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    links:
      - mysql
    command: npm run start-dev
  client:
    build: ./client
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web interface
volumes:
  mysql-data: